### ISSUE TITLE
I want to train it on .png 4 class images . What changes need to be made in code?

### ISSUE THREAD

**Issue by manvirvirk** [Abhishek-Iyer1/emotion-classifcation-eeg-seed-ensemble#1]

**Comment by Abhishek-Iyer1** [comment]
You should convert your images into a numpy array and concatenate all the images with their corresponding class using one hot encoding. For 4 classes, one hot encoding would be something like this. 1 -> [1, 0, 0, 0], 2-> [0,1, 0, 0] and so on so forth. Once this is ready, you can change the input and output layers of all models to match the input features (resolution of image) and output features (no. of classes). Hope this helps you get started.
