### ISSUE TITLE
What is the form of DE_data_all_corrected.mat in this K_Fold_Cross_Verification file? Because the data in the original ExtractedFeatures file does not have the attribute of'data'.

### ISSUE THREAD

**Issue by wly-vitoria** [Abhishek-Iyer1/emotion-classifcation-eeg-seed-ensemble#2]

**Comment by Abhishek-Iyer1** [comment]
I have just uploaded the Matlab script I wrote to concatenate and correct the Differential Entropy (DE) data of all the different experiments as given in Extracted Features file. You can use that as a reference. It should output a concatenated array which you can access using the attributed 'data' and 'label'. Hope this helps.
